version: '3.1'

services:
  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: V69Gz4wsysY
    volumes: 
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    network_mode: default

