version: '3.1'

services:
  mysql:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: V69Gz4wsysY
    ports:
      - 3306:3306
    volumes: 
      - ./mysql_data:/var/lib/mysql
    network_mode: default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    network_mode: default

  exporter:
    # https://github.com/prometheus/mysqld_exporter
    network_mode: default
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    environment:
      DATA_SOURCE_NAME: "root:V69Gz4wsysY@(db:3306)"
    entrypoint:
      - /bin/mysqld_exporter
      - --collect.auto_increment.columns
      - --collect.global_status
      - --collect.info_schema.innodb_cmp
      - --collect.perf_schema.eventswaits
      - --collect.perf_schema.eventsstatementssum
      - --collect.perf_schema.indexiowaits
      - --collect.perf_schema.tablelocks
      - --collect.slave_status
      # - --no-collect.auto_increment.columns

